jobs:
  vault-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Vault CLI
      uses: hashicorp/setup-vault@v1
      with:
        vault_version: "1.10.0"

    - name: Authenticate with Vault (AppRole example)
      run: |
        export VAULT_ADDR=https://your-vault-server.com
        export VAULT_ROLE_ID=${{ secrets.VAULT_ROLE_ID }}
        export VAULT_SECRET_ID=${{ secrets.VAULT_SECRET_ID }}
        vault login -method=approle role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID

    - name: Fetch secret from Vault
      run: |
        export SECRET_PATH="secret/data/my-app"
        vault kv get $SECRET_PATH
